name: 'C++ CI'

on:
  push:
    branches:
      - lab7
      - feature/github_actions

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      # - name: Prepare system
      #   run:  |
      #     sudo apt-get update -y && \
      #     sudo apt-get upgrade
        

      - name: Configure Cmake
        run: |
          cmake -B build -S . -DPATCH_VERSION_OVERRIDE=${{ github.run_number }}

      - name: Build
        run: |
          cmake --build build
          # cmake --build build --target tests
          cmake --build build --target package --config Release

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release create v2025.6.${{ github.run_number }} bin/*Linux.deb

  build-windows:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B build -S . -G "Visual Studio 17 2022" -A x64  -DPATCH_VERSION_OVERRIDE=${{ github.run_number }}

      - name: Build
        run: |
          cmake --build build
          cmake --build build --target package --config Release
      
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          gh release upload v2025.6.${{ github.run_number }} bin/*win64.zip
