name: 'C++ CI'

on:
  push:
    branches:
      - lab2
      - feature/github_actions

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Prepare system
        run: sudo apt-get update -y

      - name: Configure Cmake
        run: |
          cmake -B build -S .
          cmake build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: |
          cmake --build build
          cmake --build build --target package --config Release

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release create v2025.2.${{ github.run_number }} build/helloworld-2025.2.${{ github.run_number }}-Linux.deb

  build-windows:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -B build -S . -G "Visual Studio 17 2022" -A x64 
          cmake build -DPATCH_VERSION=${{ github.run_number }}

      - name: Build
        run: |
          cmake --build build
          cmake --build build --target package --config Release
      
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          gh release upload v2025.2.${{ github.run_number }} build/helloworld-2025.2.${{ github.run_number }}-win64.zip
